using System;
using System.Runtime.InteropServices;

namespace Kedacom.AutoGen
{
    public unsafe static partial class Kedacom
    {
        /// <summary>CAP_8021X = &quot;8021x&quot;</summary>
        public const string CAP_8021X = "8021x";
        /// <summary>CAP_ALARMIN = &quot;alarmin&quot;</summary>
        public const string CAP_ALARMIN = "alarmin";
        /// <summary>CAP_ALARMOUT = &quot;alarmout&quot;</summary>
        public const string CAP_ALARMOUT = "alarmout";
        /// <summary>CAP_ANALYZE = &quot;analyze&quot;</summary>
        public const string CAP_ANALYZE = "analyze";
        /// <summary>CAP_ANONYM = &quot;anonym&quot;</summary>
        public const string CAP_ANONYM = "anonym";
        /// <summary>CAP_ASSFOCUS = &quot;assfocus&quot;</summary>
        public const string CAP_ASSFOCUS = "assfocus";
        /// <summary>CAP_AUDIODEC = &quot;audiodec&quot;</summary>
        public const string CAP_AUDIODEC = "audiodec";
        /// <summary>CAP_AUDIOENC = &quot;audioenc&quot;</summary>
        public const string CAP_AUDIOENC = "audioenc";
        /// <summary>CAP_AUTOMAINTAIN = &quot;automaintain&quot;</summary>
        public const string CAP_AUTOMAINTAIN = "automaintain";
        /// <summary>CAP_BLC = &quot;blc&quot;</summary>
        public const string CAP_BLC = "blc";
        /// <summary>CAP_BLUETOOTH = &quot;bluetooth&quot;</summary>
        public const string CAP_BLUETOOTH = "bluetooth";
        /// <summary>CAP_BRIGHTNESS = &quot;brightness&quot;</summary>
        public const string CAP_BRIGHTNESS = "brightness";
        /// <summary>CAP_CONTRAST = &quot;contrast&quot;</summary>
        public const string CAP_CONTRAST = "contrast";
        /// <summary>CAP_CORRIDORMODE = &quot;corridormode&quot;</summary>
        public const string CAP_CORRIDORMODE = "corridormode";
        /// <summary>CAP_DDNS = &quot;ddns&quot;</summary>
        public const string CAP_DDNS = "ddns";
        /// <summary>CAP_DEFRONST = &quot;defronst&quot;</summary>
        public const string CAP_DEFRONST = "defronst";
        /// <summary>CAP_DETECT = &quot;detect&quot;</summary>
        public const string CAP_DETECT = "detect";
        /// <summary>CAP_DYNAMICMODE = &quot;dynamicmode&quot;</summary>
        public const string CAP_DYNAMICMODE = "dynamicmode";
        /// <summary>CAP_DYNAMICOSD = &quot;dynamicosd&quot;</summary>
        public const string CAP_DYNAMICOSD = "dynamicosd";
        /// <summary>CAP_ENCCLIP = &quot;encclip&quot;</summary>
        public const string CAP_ENCCLIP = "encclip";
        /// <summary>CAP_ESHAKE = &quot;eshake&quot;</summary>
        public const string CAP_ESHAKE = "eshake";
        /// <summary>CAP_EXCEPTION = &quot;exception&quot;</summary>
        public const string CAP_EXCEPTION = "exception";
        /// <summary>CAP_FIND = &quot;find&quot;</summary>
        public const string CAP_FIND = "find";
        /// <summary>CAP_FOCUS = &quot;focus&quot;</summary>
        public const string CAP_FOCUS = "focus";
        /// <summary>CAP_FOGTHROUGH = &quot;fogthrough&quot;</summary>
        public const string CAP_FOGTHROUGH = "fogthrough";
        /// <summary>CAP_GAIN = &quot;gain&quot;</summary>
        public const string CAP_GAIN = "gain";
        /// <summary>CAP_GAMMA = &quot;gamma&quot;</summary>
        public const string CAP_GAMMA = "gamma";
        /// <summary>CAP_GB28181 = &quot;gb28181&quot;</summary>
        public const string CAP_GB28181 = "gb28181";
        /// <summary>CAP_HDSDI = &quot;hdsdi&quot;</summary>
        public const string CAP_HDSDI = "hdsdi";
        /// <summary>CAP_HELP = &quot;help&quot;</summary>
        public const string CAP_HELP = "help";
        /// <summary>CAP_HLC = &quot;hlc&quot;</summary>
        public const string CAP_HLC = "hlc";
        /// <summary>CAP_HUE = &quot;hue&quot;</summary>
        public const string CAP_HUE = "hue";
        /// <summary>CAP_IMAGE = &quot;image&quot;</summary>
        public const string CAP_IMAGE = "image";
        /// <summary>CAP_IMAGEENHANCE = &quot;imageenhance&quot;</summary>
        public const string CAP_IMAGEENHANCE = "imageenhance";
        /// <summary>CAP_IMAGEMODE = &quot;imagemode&quot;</summary>
        public const string CAP_IMAGEMODE = "imagemode";
        /// <summary>CAP_IMAGETRUN = &quot;imagetrun&quot;</summary>
        public const string CAP_IMAGETRUN = "imagetrun";
        /// <summary>CAP_INFRARED = &quot;infrared&quot;</summary>
        public const string CAP_INFRARED = "infrared";
        /// <summary>CAP_IPADDR = &quot;ipaddr&quot;</summary>
        public const string CAP_IPADDR = "ipaddr";
        /// <summary>CAP_IRCUTFILTER = &quot;ircutfilter&quot;</summary>
        public const string CAP_IRCUTFILTER = "ircutfilter";
        /// <summary>CAP_IRIS = &quot;iris&quot;</summary>
        public const string CAP_IRIS = "iris";
        /// <summary>CAP_KSNMP = &quot;ksnmp&quot;</summary>
        public const string CAP_KSNMP = "ksnmp";
        /// <summary>CAP_LASER = &quot;laser&quot;</summary>
        public const string CAP_LASER = "laser";
        /// <summary>CAP_LIMIT = &quot;limit&quot;</summary>
        public const string CAP_LIMIT = "limit";
        /// <summary>CAP_LOCALECHO = &quot;localecho&quot;</summary>
        public const string CAP_LOCALECHO = "localecho";
        /// <summary>CAP_LOG = &quot;log&quot;</summary>
        public const string CAP_LOG = "log";
        /// <summary>CAP_MTCF = &quot;mtcf&quot;</summary>
        public const string CAP_MTCF = "mtcf";
        /// <summary>CAP_MULCARD = &quot;mulcard&quot;</summary>
        public const string CAP_MULCARD = "mulcard";
        /// <summary>CAP_NOISEREDUCE2D = &quot;noisereduce2d&quot;</summary>
        public const string CAP_NOISEREDUCE2D = "noisereduce2d";
        /// <summary>CAP_NOISEREDUCE3D = &quot;noisereduce3d&quot;</summary>
        public const string CAP_NOISEREDUCE3D = "noisereduce3d";
        /// <summary>CAP_ONVIF = &quot;onvif&quot;</summary>
        public const string CAP_ONVIF = "onvif";
        /// <summary>CAP_OSD = &quot;osd&quot;</summary>
        public const string CAP_OSD = "osd";
        /// <summary>CAP_PATHCRUISE = &quot;pathcruise&quot;</summary>
        public const string CAP_PATHCRUISE = "pathcruise";
        /// <summary>CAP_PATTERNS = &quot;patterns&quot;</summary>
        public const string CAP_PATTERNS = "patterns";
        /// <summary>CAP_POWERLINEFREQUENCY = &quot;powerlinefrequency&quot;</summary>
        public const string CAP_POWERLINEFREQUENCY = "powerlinefrequency";
        /// <summary>CAP_PPPOE = &quot;pppoe&quot;</summary>
        public const string CAP_PPPOE = "pppoe";
        /// <summary>CAP_PRESET = &quot;preset&quot;</summary>
        public const string CAP_PRESET = "preset";
        /// <summary>CAP_PTZ = &quot;ptz&quot;</summary>
        public const string CAP_PTZ = "ptz";
        /// <summary>CAP_QOS = &quot;qos&quot;</summary>
        public const string CAP_QOS = "qos";
        /// <summary>CAP_REC = &quot;rec&quot;</summary>
        public const string CAP_REC = "rec";
        /// <summary>CAP_ROI = &quot;roi&quot;</summary>
        public const string CAP_ROI = "roi";
        /// <summary>CAP_RS232 = &quot;rs232&quot;</summary>
        public const string CAP_RS232 = "rs232";
        /// <summary>CAP_RS485 = &quot;rs485&quot;</summary>
        public const string CAP_RS485 = "rs485";
        /// <summary>CAP_SATURATION = &quot;saturation&quot;</summary>
        public const string CAP_SATURATION = "saturation";
        /// <summary>CAP_SECURITY = &quot;security&quot;</summary>
        public const string CAP_SECURITY = "security";
        /// <summary>CAP_SHAKE = &quot;shake&quot;</summary>
        public const string CAP_SHAKE = "shake";
        /// <summary>CAP_SHIELDALARM = &quot;shieldalarm&quot;</summary>
        public const string CAP_SHIELDALARM = "shieldalarm";
        /// <summary>CAP_SHUTTER = &quot;shutter&quot;</summary>
        public const string CAP_SHUTTER = "shutter";
        /// <summary>CAP_SMARTIR = &quot;smartir&quot;</summary>
        public const string CAP_SMARTIR = "smartir";
        /// <summary>CAP_SNAPPIC = &quot;snappic&quot;</summary>
        public const string CAP_SNAPPIC = "snappic";
        /// <summary>CAP_STORAGE = &quot;storage&quot;</summary>
        public const string CAP_STORAGE = "storage";
        /// <summary>CAP_STREAMNUM = &quot;streamnum&quot;</summary>
        public const string CAP_STREAMNUM = "streamnum";
        /// <summary>CAP_TIMETASK = &quot;timetask&quot;</summary>
        public const string CAP_TIMETASK = "timetask";
        /// <summary>CAP_VIDEOSHILD = &quot;videoshild&quot;</summary>
        public const string CAP_VIDEOSHILD = "videoshild";
        /// <summary>CAP_VIDEOSOURCENUM = &quot;videosourcenum&quot;</summary>
        public const string CAP_VIDEOSOURCENUM = "videosourcenum";
        /// <summary>CAP_VISP = &quot;visp&quot;</summary>
        public const string CAP_VISP = "visp";
        /// <summary>CAP_WATCHON = &quot;watchon&quot;</summary>
        public const string CAP_WATCHON = "watchon";
        /// <summary>CAP_WDR = &quot;wdr&quot;</summary>
        public const string CAP_WDR = "wdr";
        /// <summary>CAP_WHITEBALANCE = &quot;whitebalance&quot;</summary>
        public const string CAP_WHITEBALANCE = "whitebalance";
        /// <summary>CAP_WIFI = &quot;wifi&quot;</summary>
        public const string CAP_WIFI = "wifi";
        /// <summary>CAP_WIPER = &quot;wiper&quot;</summary>
        public const string CAP_WIPER = "wiper";
        /// <summary>CAP_WIRELESS = &quot;wireless&quot;</summary>
        public const string CAP_WIRELESS = "wireless";
        // public static CDECL = __cdecl;
        /// <summary>DEF_ = (80)</summary>
        public const int DEF_ = 0x50;
        /// <summary>ERR_ANALVZE = (10)</summary>
        public const int ERR_ANALVZE = 0xa;
        /// <summary>ERR_AUCFAILD = (6)</summary>
        public const int ERR_AUCFAILD = 0x6;
        /// <summary>ERR_AUTHID = (205)</summary>
        public const int ERR_AUTHID = 0xcd;
        /// <summary>ERR_CHECK = (216)</summary>
        public const int ERR_CHECK = 0xd8;
        /// <summary>ERR_DEVICE_BUSY = (229)</summary>
        public const int ERR_DEVICE_BUSY = 0xe5;
        /// <summary>ERR_DEVICELOSE = (14)</summary>
        public const int ERR_DEVICELOSE = 0xe;
        /// <summary>ERR_DNS = (223)</summary>
        public const int ERR_DNS = 0xdf;
        /// <summary>ERR_FILE = (217)</summary>
        public const int ERR_FILE = 0xd9;
        /// <summary>ERR_GATEWAY = (222)</summary>
        public const int ERR_GATEWAY = 0xde;
        /// <summary>ERR_HTTPSEND = (9)</summary>
        public const int ERR_HTTPSEND = 0x9;
        /// <summary>ERR_INITFAILD = (4)</summary>
        public const int ERR_INITFAILD = 0x4;
        /// <summary>ERR_INVALID_ARG = (228)</summary>
        public const int ERR_INVALID_ARG = 0xe4;
        /// <summary>ERR_IP = (220)</summary>
        public const int ERR_IP = 0xdc;
        /// <summary>ERR_IP_DENY = (207)</summary>
        public const int ERR_IP_DENY = 0xcf;
        /// <summary>ERR_MASK = (221)</summary>
        public const int ERR_MASK = 0xdd;
        /// <summary>ERR_MEMERYFAILD = (7)</summary>
        public const int ERR_MEMERYFAILD = 0x7;
        /// <summary>ERR_MTU = (225)</summary>
        public const int ERR_MTU = 0xe1;
        /// <summary>ERR_MULTICAST = (224)</summary>
        public const int ERR_MULTICAST = 0xe0;
        /// <summary>ERR_NEED_BODY = (211)</summary>
        public const int ERR_NEED_BODY = 0xd3;
        /// <summary>ERR_NEED_REQUERY = (233)</summary>
        public const int ERR_NEED_REQUERY = 0xe9;
        /// <summary>ERR_NO_POWER = (206)</summary>
        public const int ERR_NO_POWER = 0xce;
        /// <summary>ERR_NODEFINE = (13)</summary>
        public const int ERR_NODEFINE = 0xd;
        /// <summary>ERR_NODLL = (2)</summary>
        public const int ERR_NODLL = 0x2;
        /// <summary>ERR_NOFORMAT = (2509)</summary>
        public const int ERR_NOFORMAT = 0x9cd;
        /// <summary>ERR_NOFUN = (3)</summary>
        public const int ERR_NOFUN = 0x3;
        /// <summary>ERR_NOLOGIN = (12)</summary>
        public const int ERR_NOLOGIN = 0xc;
        /// <summary>ERR_NOT_AUTH = (203)</summary>
        public const int ERR_NOT_AUTH = 0xcb;
        /// <summary>ERR_OLDPASS = (208)</summary>
        public const int ERR_OLDPASS = 0xd0;
        /// <summary>ERR_PARAM = (8)</summary>
        public const int ERR_PARAM = 0x8;
        /// <summary>ERR_PARAM_LOST = (214)</summary>
        public const int ERR_PARAM_LOST = 0xd6;
        /// <summary>ERR_PARMM_TOOLONG = (215)</summary>
        public const int ERR_PARMM_TOOLONG = 0xd7;
        /// <summary>ERR_PASS = (204)</summary>
        public const int ERR_PASS = 0xcc;
        /// <summary>ERR_RECOVER = (230)</summary>
        public const int ERR_RECOVER = 0xe6;
        /// <summary>ERR_RELEASE = (5)</summary>
        public const int ERR_RELEASE = 0x5;
        /// <summary>ERR_SEQ = (226)</summary>
        public const int ERR_SEQ = 0xe2;
        /// <summary>ERR_UNKNOW = (201)</summary>
        public const int ERR_UNKNOW = 0xc9;
        /// <summary>ERR_UPGRADE_FAILURE = (218)</summary>
        public const int ERR_UPGRADE_FAILURE = 0xda;
        /// <summary>ERR_UPLOADING = (11)</summary>
        public const int ERR_UPLOADING = 0xb;
        /// <summary>ERR_URL = (227)</summary>
        public const int ERR_URL = 0xe3;
        /// <summary>ERR_URL_NO_SUPPORT = (210)</summary>
        public const int ERR_URL_NO_SUPPORT = 0xd2;
        /// <summary>ERR_USER_ACTIVE = (232)</summary>
        public const int ERR_USER_ACTIVE = 0xe8;
        /// <summary>ERR_USER_BANNED = (231)</summary>
        public const int ERR_USER_BANNED = 0xe7;
        /// <summary>ERR_USER_EXIST = (209)</summary>
        public const int ERR_USER_EXIST = 0xd1;
        /// <summary>ERR_USERNAME = (202)</summary>
        public const int ERR_USERNAME = 0xca;
        /// <summary>ERR_XML = (212)</summary>
        public const int ERR_XML = 0xd4;
        /// <summary>ERR_XML_PARAM = (219)</summary>
        public const int ERR_XML_PARAM = 0xdb;
        /// <summary>ERR_XML_ROOT = (213)</summary>
        public const int ERR_XML_ROOT = 0xd5;
        /// <summary>EVT_PTZ_BEGIN = (0)</summary>
        public const int EVT_PTZ_BEGIN = 0x0;
        /// <summary>EVT_PTZ_FOUCUS = (EVT_PTZ_BEGIN + 1)</summary>
        public const int EVT_PTZ_FOUCUS = EVT_PTZ_BEGIN + 0x1;
        /// <summary>FALSE = 0x0</summary>
        public const int FALSE = 0x0;
        // public static IPC_API = extern "C" __declspec(dllexport);
        // public static KD_PTR = void*;
        /// <summary>MAX_DEV_NAME = 64</summary>
        public const int MAX_DEV_NAME = 0x40;
        /// <summary>MAX_EXPAND_PATH = 1024</summary>
        public const int MAX_EXPAND_PATH = 0x400;
        /// <summary>MAX_PATH = 0x104</summary>
        public const int MAX_PATH = 0x104;
        /// <summary>MAX_PROTOCOL_NAME = 32</summary>
        public const int MAX_PROTOCOL_NAME = 0x20;
        /// <summary>MAX_USER_NAME = 64</summary>
        public const int MAX_USER_NAME = 0x40;
        /// <summary>MAX_USER_PASSWORD = 64</summary>
        public const int MAX_USER_PASSWORD = 0x40;
        /// <summary>NORMAL_BEGIN = 0</summary>
        public const int NORMAL_BEGIN = 0x0;
        /// <summary>NULL = 0</summary>
        public const int NULL = 0x0;
        /// <summary>PORT_HTTP = (80)</summary>
        public const int PORT_HTTP = 0x50;
        /// <summary>PORT_PRINT = (3700)</summary>
        public const int PORT_PRINT = 0xe74;
        /// <summary>PORT_RTSP = (554)</summary>
        public const int PORT_RTSP = 0x22a;
        // public static PROCADDR = GetProcAddress;
        /// <summary>REC_TCP = (NORMAL_BEGIN + 2)</summary>
        public const int REC_TCP = NORMAL_BEGIN + 0x2;
        /// <summary>RET_FAILD = (0)</summary>
        public const int RET_FAILD = 0x0;
        /// <summary>RET_SUCCESS = (1)</summary>
        public const int RET_SUCCESS = 0x1;
        /// <summary>TRUE = 0x1</summary>
        public const int TRUE = 0x1;
        /// <summary>VIEW_TCP = (NORMAL_BEGIN + 2)</summary>
        public const int VIEW_TCP = NORMAL_BEGIN + 0x2;
        /// <summary>VIEW_UDP = (NORMAL_BEGIN + 3)</summary>
        public const int VIEW_UDP = NORMAL_BEGIN + 0x3;
    }
}
